#!/bin/bash
#
# Use pandoc to generate HTML from Markdown

mkdir -p _site

for file in *.md
do
    pandoc \
        --data-dir=_layout \
        --template=swc \
        -f markdown -t html5 \
        -o _site/${file/\.md/\.html} ${file}
done
